Adds ascii reader & points without compile-time layout.
Mortano/pasture pull request #2
Opened 2021-07-05 17:00 UTC by TomTroppmann

2021-07-07 07:02 UTC, Mortano requested changes
Looks good in general, just some small comments. The documentation and the UntypedPoint stuff should be changed IMO.

2021-07-07 07:02 UTC, Mortano commented on pasture-io/Cargo.toml
> +nalgebra = {version = "0.23.1", features = ["serde-serialize"] }
pasture-core exposes nalgebra, so you could use that one instead. This way there won't be any problems when pasture-core goes up to a newer nalgebra version

2021-07-07 07:02 UTC, Mortano commented on pasture-io/src/ascii/ascii_reader.rs
> +/// `PointReader` implementation for ascii files
More documentation would be good here, especially showing the usage of the format literals.

2021-07-07 07:02 UTC, Mortano commented on pasture-io/src/ascii/raw_reader.rs
> +            .for_each(|attribute| attributes.push_unique(attribute));
You can use `.collect::<HashSet<_>>()` here, instead of this `push_unique` thing that you implemented. You might have to add an implementation of the `Hash` trait to `PointAttributeDefinition`, but that seems reasonable.

2021-07-07 07:02 UTC, Mortano commented on pasture-io/src/ascii/raw_reader.rs
> +trait VecPushUnique<T: PartialEq>: Sized {
See comment above, this trait should not be needed

2021-07-07 07:02 UTC, Mortano commented on pasture-io/src/ascii/raw_reader.rs
> +            let point = Self::get_point(&line, &self.delimiter, &self.parse_layout, &layout)
I get why you implemented `UntypedPoint`, however since it uses a `Vec<u8>` internally, thats a dynamic allocation for every point. How about changing `get_point` to instead take a `&mut Cursor<[u8]>` instead of returning a new `UntypedPoint`? This would have two advantages:

1. You have to create just one `UntypedPoint` (-> just one allocation) and can reuse it within the loop
2. There is a [`resize()` method in the works for the `PointBufferWriteable` trait](https://github.com/Mortano/pasture/blob/37b3b612e4136c1c2549c4fcedb7b8752ebd52a4/pasture-core/src/containers/point_buffer.rs#L120), once this has been merged you can then use this to resize the buffer once, get a mutable slice to its memory and write directly to the buffer in `get_point`, instead of copying from a different temporary buffer

2021-07-07 07:02 UTC, Mortano commented on pasture-io/src/ascii/raw_reader.rs
> +        //Check 3d Positions
This test should check all point attributes of `TestPointSame`, not just positions

2021-07-07 07:02 UTC, Mortano commented on pasture-io/src/ascii/raw_reader.rs
> +        //Check 3d Positions
This test especially should check all attributes of `TestPointDifferent`. How are point attributes treated that are not found in the file? Probably default-constructed, but the test should verify this

2021-07-07 07:02 UTC, Mortano commented on pasture-io/src/ascii/raw_reader.rs
> +        assert!(format!("{:?}", ascii_reader.err().unwrap())
You can also use a `#[should_panic(expected = "...")]` macro on the test function to check the same thing. To make it work, just `unwrap()` the `ascii_reader`.

2021-07-07 15:27 UTC, TomTroppmann commented
@Mortano All requested changes should be addressed. Open for more comments.

2021-07-14 20:59 UTC, remunds commented on pasture-core/src/containers/untyped_point.rs
> +    pub fn get_interlieved_point_view(&self) -> InterleavedPointView {
think there is a wee typo here -> interleaved

(i am just here because i also want to use untyped_point :smile: )

2021-07-16 06:45 UTC, merged