adds voxelgrid-filter algorithms
Mortano/pasture pull request #7
Opened 2021-08-01 15:32 UTC by remunds

2021-08-04 06:06 UTC, Mortano requested changes
Thanks for this PR. Looks good overall, however there is one potential crash here from what I can see, this should be fixed (`panic` is fine).

2021-08-04 06:06 UTC, Mortano commented on pasture-algorithms/src/voxel_grid.rs
> +                        .to_string(),
It might be better to write this whole method as generic over `<..., U: PrimitiveType>`. I don't think converting to a string to store the attributes inside the map is very fast. I guess it is ok for now, but please add a `TODO` comment that this is a workaround.

2021-08-04 06:06 UTC, Mortano commented on pasture-algorithms/src/voxel_grid.rs
> +            PointAttributeDataType::Bool => panic!("Boolean type cannot be averaged."),
You don't have to write every match case here, you can also match on the remaining cases using `_ => panic!("Invalid data type for centroid_average_vec")`

2021-08-04 06:06 UTC, Mortano commented on pasture-algorithms/src/voxel_grid.rs
> +            &centroid.set_attribute(&attributes::POSITION_3D, pos_slice);
This will crash if `centroid` has `POSITION_3D` with a different data type than `Vector3<f64>`. Either use a converter from [here](https://github.com/Mortano/pasture/blob/main/pasture-core/src/layout/conversion.rs) or check that the attribute `a` has data type `Vector3<f64>` (`PointAttributeDataType::Vec3f64`). Same for all of the following if-cases

2021-08-04 06:06 UTC, Mortano commented on pasture-algorithms/src/voxel_grid.rs
> +        } else if &a.name() == &attributes::WAVE_PACKET_DESCRIPTOR_INDEX.name() {
I think the waveform data makes no sense in this algorithm. You can comment it out, maybe there will be a use-case for it in the future, but for now we can just have the method check that the layout of the `filtered_buffer` does not contain any of the waveform values. 

A future version of this algorithm should take a separate object that contains a mapping between point attributes and the desired type of 'reduction function'. This way we could store defaults in this object but have the users overwrite the defaults with whatever they want.

2021-08-24 15:24 UTC, remunds commented
All requested changes should now be done and the merge conflicts resolved.

2021-09-14 11:25 UTC, merged